name: farm_well
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=3.3.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.31.0
  firebase_auth: ^4.19.5
  cloud_firestore: ^4.17.3
  google_sign_in: ^6.2.1
  image_picker: ^0.8.6+1
  carousel_slider: ^4.2.1
  provider: ^6.1.2
  firebase_storage: ^11.7.5
  http: ^1.2.1
  flutter_native_splash: ^2.0.6
  animated_text_kit: ^4.2.1
  intl: ^0.17.0
  url_launcher: ^6.0.3
  flutter_launcher_icons: ^0.11.0
  image_cropper: ^7.1.0
  image: ^3.0.2
  flutter_email_sender: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter_native_splash:
  color: "#42a5f5" # Background color of the splash screen
  image: images/splash.jpeg
  android: true # Include Android
  ios: true # Include iOS

flutter_icons:
  android: true
  ios: true
  image_path: "images/splash.jpeg"

flutter:
  uses-material-design: true

  assets:
    - images/car.PNG
    - images/google.png
    - images/noData.png
    - images/aifarm.jpg
    - images/plant_background.jpeg
    - images/profile_image.jpeg
    - images/tomato_leaf_blight.jpeg
    - images/citrus_greening.jpeg
    - images/prediction1.jpeg
    - images/prediction2.jpeg
    - images/splash.jpeg
    - images/potato.jpeg
    - images/orange.jpeg
    - images/pepper.jpeg
    - images/rice.jpeg
    - images/soyabean.jpeg
    - images/tomato.jpeg
    - images/cashew.jpeg
    - images/cassava.jpeg
    - images/maize.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
