// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrEzGJPK1sJ0Xg2mhD4akj7jnF0xaqDB8',
    appId: '1:868737949553:web:00de72b15efecb745060d0',
    messagingSenderId: '868737949553',
    projectId: 'farm-well',
    authDomain: 'farm-well.firebaseapp.com',
    storageBucket: 'farm-well.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUuaGlSE_Y5Y27IapCjtJ2E0Nt-Ywu2c',
    appId: '1:868737949553:android:0ef33a880b556f0d5060d0',
    messagingSenderId: '868737949553',
    projectId: 'farm-well',
    storageBucket: 'farm-well.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfYpRkKbUl5W35Jm9ifj1WW9sNkEM6BZU',
    appId: '1:868737949553:ios:2b366380fe0d9b475060d0',
    messagingSenderId: '868737949553',
    projectId: 'farm-well',
    storageBucket: 'farm-well.appspot.com',
    iosBundleId: 'com.example.farmWell',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfYpRkKbUl5W35Jm9ifj1WW9sNkEM6BZU',
    appId: '1:868737949553:ios:2b366380fe0d9b475060d0',
    messagingSenderId: '868737949553',
    projectId: 'farm-well',
    storageBucket: 'farm-well.appspot.com',
    iosBundleId: 'com.example.farmWell',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDrEzGJPK1sJ0Xg2mhD4akj7jnF0xaqDB8',
    appId: '1:868737949553:web:e5d2630ac4c813155060d0',
    messagingSenderId: '868737949553',
    projectId: 'farm-well',
    authDomain: 'farm-well.firebaseapp.com',
    storageBucket: 'farm-well.appspot.com',
  );

}